definitions:
  environment:
    shared_env: &shared_env
      flutter: 3.22.3
      groups:
        - shorebird
        - selleri-stage
      vars:
        FLUTTER_VERSION: 3.22.3
  scripts:
    - &create_env
      name: Create .env
      script: |
        touch "$CM_BUILD_DIR/.env"
          cat >> "$CM_BUILD_DIR/.env" <<EOF
          GRANT_TYPE=password
          CLIENT_ID=2
          HOST=https://selleri.co.id/api
          CLIENT_SECRET=7lJC833F5COjxMfFGS9xcLoPFEmKTIXnf6gYClKR
          APP_ID=selleri
          EOF
    - &create_env_stage
      name: Create .env.stage
      script: |
        touch "$CM_BUILD_DIR/.env.stage"
          cat >> "$CM_BUILD_DIR/.env.stage" <<EOF
          GRANT_TYPE=password
          CLIENT_ID=2
          HOST=https://dev.selleri.co.id/api
          CLIENT_SECRET=7lJC833F5COjxMfFGS9xcLoPFEmKTIXnf6gYClKR
          APP_ID=dev-selleri
          EOF
    - &shorebird_install
      name: Install Shorebird
      script: |
        # Install Shorebird
        curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash

        # Add Shorebird to PATH
        echo PATH="$HOME/.shorebird/bin:$PATH" >> $CM_ENV
    - &fetch_dependencies
      name: Fetch Dependencies
      script: |
        flutter pub get
    - &build_runner
      name: Build Runner
      script: |
        dart run build_runner build -d
    - &analyze_and_test
      name: Analyze and Test
      script: |
        flutter analyze

workflows:
  release-android-stage-workflow:
    name: Release Android Stage
    instance_type: mac_mini_m1
    environment:
      <<: *shared_env
      android_signing:
        - selleri_stage_keystore
    scripts:
      - *shorebird_install
      - *fetch_dependencies
      - *build_runner
      - *analyze_and_test
      - name: Shorebird Release
        script: |
          shorebird release android \
            --flavor=stage --flutter-version="$FLUTTER_VERSION" --artifact apk
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log

  patch-android-stage-workflow:
    name: Patch Android
    instance_type: mac_mini_m1
    environment:
      <<: *shared_env
      android_signing:
        - selleri_stage_keystore
    inputs:
      release_version:
        description: The stage version to patch
    scripts:
      - *shorebird_install
      - *create_env
      - *create_env_stage
      - *fetch_dependencies
      - *build_runner
      - *analyze_and_test
      - name: Shorebird Patch
        script: |
          shorebird patch android \
            --flavor=stage --release-version=${{ inputs.release_version }}
