name: selleri
description: 'Selleri POS'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.1.1
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  get: ^4.6.6
  get_storage: ^2.1.1
  intl: ^0.19.0
  objectbox: ^2.4.0
  objectbox_flutter_libs: ^2.4.0
  responsive_framework: ^1.1.1
  validators: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  objectbox_generator: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - .env
