name: selleri
description: "Selleri POS"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.2.3+9

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  camera: ^0.11.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.2
  currency_text_input_formatter: ^2.2.3
  device_info_plus: ^11.2.2
  dio: ^5.4.0
  easy_localization: ^3.0.6
  equatable: ^2.0.5
  esc_pos_utils_plus: ^2.0.4
  firebase_analytics: ^11.3.6
  firebase_core: ^3.10.1
  firebase_crashlytics: ^4.3.1
  firebase_messaging: ^15.1.3
  flutter:
    sdk: flutter
  flutter_barcode_listener: ^0.1.4
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^18.0.1
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^10.0.0-beta.4
  fluttertoast: ^8.2.6
  freezed_annotation: ^2.4.1
  get_storage: ^2.1.1
  go_router: ^14.6.2
  grouped_list: ^6.0.0
  image: ^4.2.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  mobile_scanner: ^6.0.5
  objectbox: ^4.0.3
  objectbox_flutter_libs: ^4.0.3
  open_file: ^3.5.10
  package_info_plus: ^8.0.0
  patch_package: ^0.0.8
  path: ^1.9.0
  path_provider: ^2.1.3
  pdf: ^3.11.0
  permission_handler: ^11.3.1
  print_bluetooth_thermal: ^1.1.4
  responsive_framework: ^1.1.1
  restart_app: ^1.3.2
  riverpod_annotation: ^2.3.5
  screenshot: ^3.0.0
  share_plus: ^10.0.0
  shorebird_code_push: ^2.0.2
  super_tooltip: ^2.0.9
  syncfusion_flutter_datepicker: ^28.2.4
  url_launcher: ^6.3.1
  uuid: ^4.4.0
  validators: ^3.0.0
  visibility_detector: ^0.4.0+2
  wakelock_plus: ^1.2.10

dev_dependencies:
  build_runner: ^2.4.9
  change_app_package_name: ^1.2.0
  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  objectbox_generator: ^4.0.3
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

# dependency_overrides:
#   rxdart: ^0.27.7
flutter:
  uses-material-design: true
  assets:
    - .env.stage
    - .env
    - assets/images/
    - assets/translations/
    - shorebird.yaml
