// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF3ioqyBnzSCjVwwPPtlECgsOFMCh05kg',
    appId: '1:107680786292:android:33ce365eb80fcee83cee21',
    messagingSenderId: '107680786292',
    projectId: 'selleri-486e6',
    databaseURL: 'https://selleri-486e6.firebaseio.com',
    storageBucket: 'selleri-486e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwdSF-h8TkFuNsigTAGFYffxactoLkY7U',
    appId: '1:107680786292:ios:25e36a95642325833cee21',
    messagingSenderId: '107680786292',
    projectId: 'selleri-486e6',
    databaseURL: 'https://selleri-486e6.firebaseio.com',
    storageBucket: 'selleri-486e6.appspot.com',
    androidClientId: '107680786292-md9uile1r6mdrp4496ft1jqh9vlbssql.apps.googleusercontent.com',
    iosBundleId: 'com.dgti.selleri',
  );

}